name: WarFare-Battlefronts-MinecraftPlugin
version: '0.1'
main: de.epax.warFareBattlefrontsMinecraftPlugin.WarFareBattlefrontsMinecraftPlugin
api-version: '1.21'
authors: [ EPAXGAMING ]
description: New plugin lol lol
commands:
  gm:
  gamemode:
  fly:
  unban:
  vanish:
  v:

